version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always 
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdtuto
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: 'redis:7-alpine'
    restart: always 
    container_name: redis_db
    command: redis-server --requirepass redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  bot: 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    container_name: bot_app
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: node /app/bot

  task: 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    container_name: task_app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: node /app/bot/task.js
    
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    container_name: web_app
    environment:
      ENV: production
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: npm start --host 0.0.0.0
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
  node_modules: